/* ═══════════════════════════════════════════════════════════════════════════
 * POST /api/admin/content-creator/[id]/publish-to-pages
 *
 * Sends a finalized GEO draft over to the CMS-side `pages` table (the
 * block-editor CMS used by /admin/cms/pages) as an UNPUBLISHED page with
 * category='geo'. Admin toggles it live from /admin/cms/pages. Mirrors
 * /publish-to-blog for the blog side.
 *
 * Idempotent: if this draft was already published, the existing page row
 * is UPDATED in-place. Response says which path ran via `created`.
 *
 * Preconditions:
 *   - content_type must be 'geo'
 *   - status must be 'verified' AND verification.approved_at set
 *   - brief.area_slug + brief.issue_slug must both be present
 *
 * Response on success: { page, created: boolean }
 * ═══════════════════════════════════════════════════════════════════════════ */

import { NextRequest } from 'next/server';
import { adminClient } from '@/lib/adminClient';
import { requireAdmin } from '@/lib/auth';
import { ok, err, pgError, readParams } from '@/lib/content-creator/api-helpers';
import { stripHashHeadings } from '@/lib/content-creator/length';

export const runtime = 'nodejs';

type Ctx = { params: Promise<{ id: string }> };

/* ─── Markdown → blocks ─────────────────────────────────────────────────── */

interface Block {
  id:       string;
  type:     'heading' | 'paragraph' | 'divider';
  level?:   2;
  content?: string;
}

/** Make a best-effort conversion of the draft body (markdown-ish with
 *  bold section headings, per the Apr-2026 no-`#` rule) into the block
 *  shape the pages CMS stores.
 *
 *  Rules:
 *    - Blank lines separate blocks.
 *    - A block whose sole content is wrapped in `**...**` becomes a
 *      heading-level-2 block.
 *    - A block that is `---` alone becomes a divider.
 *    - Everything else becomes a paragraph. Inline `**bold**` is
 *      preserved as `<strong>...</strong>` (HTML), matching what
 *      parseContent(…) + blocksToHtml(…) on the client round-trip to. */
function markdownToBlocks(body: string): Block[] {
  // Normalise — ensure trailing single newline before splitting, collapse
  // any `---\nSources:\n…` tail (generated by the citation post-processor)
  // so sources land in a final paragraph rather than as a divider + list.
  const text = body.replace(/\r\n/g, '\n').trim();

  const out: Block[] = [];
  let idx = 0;
  const mkId = () => `block_${Date.now()}_${idx++}_${Math.random().toString(36).slice(2, 9)}`;

  // Split on 2+ consecutive blank lines. Single newlines inside a group
  // stay as <br>-joined paragraphs because the WYSIWYG editor treats
  // them that way on roundtrip.
  const groups = text.split(/\n{2,}/);

  for (const rawGroup of groups) {
    const group = rawGroup.trim();
    if (!group) continue;

    // Divider
    if (/^-{3,}$/.test(group)) {
      out.push({ id: mkId(), type: 'divider' });
      continue;
    }

    // Heading — whole group is `**...**`, single line.
    const headingMatch = /^\*\*(.+?)\*\*$/.exec(group);
    if (headingMatch && !group.includes('\n')) {
      out.push({
        id:      mkId(),
        type:    'heading',
        level:   2,
        content: headingMatch[1].trim(),
      });
      continue;
    }

    // Paragraph. Convert inline **bold** → <strong>...</strong>, keep
    // internal newlines as <br> so line-breaks inside a group survive.
    const html = escapeHtml(group)
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/\n/g, '<br/>');
    out.push({ id: mkId(), type: 'paragraph', content: html });
  }

  // Guarantee at least one block so the editor doesn't choke on empty.
  if (out.length === 0) {
    out.push({ id: mkId(), type: 'paragraph', content: '' });
  }
  return out;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

/* ─── Slug helpers ──────────────────────────────────────────────────────── */

/** Combined area+issue slug becomes the page slug. We don't re-derive
 *  from the title because the admin might edit the title later and the
 *  canonical URL shouldn't drift. */
function buildSlug(areaSlug: string, issueSlug: string): string {
  return `${areaSlug}-${issueSlug}`;
}

/** Same collision-resolution pattern as publish-to-blog. Excludes the
 *  row we're about to update so a no-op re-publish doesn't fight itself
 *  for its own slug. */
async function reserveSlug(
  sb: ReturnType<typeof adminClient>,
  base: string,
  excludeId: string | null,
): Promise<string> {
  for (let i = 0; i < 50; i++) {
    const candidate = i === 0 ? base : `${base}-${i + 1}`;
    let q = sb.from('pages').select('id').eq('slug', candidate).limit(1);
    if (excludeId) q = q.neq('id', excludeId);
    const { data } = await q;
    if (!data || data.length === 0) return candidate;
  }
  return `${base}-${Date.now()}`;
}

/** First non-empty paragraph, markdown-stripped, capped for meta_desc. */
function deriveExcerpt(body: string): string {
  const firstPara = body
    .split(/\n{2,}/)
    .map((p) => p.trim())
    .find((p) => p.length > 0 && !p.startsWith('---') && !/^\*\*.+\*\*$/.test(p));
  if (!firstPara) return '';
  return firstPara
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/[_*`~]/g, '')
    .slice(0, 300)
    .trim();
}

/* ─── Route ─────────────────────────────────────────────────────────────── */

export const POST = requireAdmin(async (_req: NextRequest, ctx?: Ctx) => {
  const { id } = await readParams(ctx);
  const sb = adminClient();

  /* Load + gate */
  const { data: draft, error: loadErr } = await sb
    .from('content_drafts')
    .select('id, content_type, status, title, body, verification, brief')
    .eq('id', id)
    .single();
  if (loadErr) return pgError(loadErr);

  if (draft.content_type !== 'geo') {
    return err(
      `Only GEO drafts can be published to /admin/cms/pages (this draft is '${draft.content_type}').`,
      400,
    );
  }
  if (draft.status !== 'verified' || !draft.verification?.approved_at) {
    return err(`Draft must be verified and finalized before publishing.`, 409);
  }

  const title = (draft.title ?? '').trim();
  if (!title) return err(`Draft has no title — publish requires one.`, 400);
  const body = (draft.body ?? '').trim();
  if (body.length < 50) return err(`Draft body is too short to publish (< 50 characters).`, 400);

  const areaSlug  = draft.brief?.area_slug  as string | undefined;
  const issueSlug = draft.brief?.issue_slug as string | undefined;
  if (!areaSlug || !issueSlug) {
    return err(`GEO draft is missing area_slug or issue_slug — cannot build page slug.`, 400);
  }

  /* Existing row? */
  const { data: existing } = await sb
    .from('pages')
    .select('id, slug')
    .eq('source_draft_id', id)
    .maybeSingle();

  const desiredSlug = buildSlug(areaSlug, issueSlug);
  const targetSlug = existing && existing.slug === desiredSlug
    ? existing.slug
    : await reserveSlug(sb, desiredSlug, existing?.id ?? null);

  const cleanBody = stripHashHeadings(body);
  const excerpt   = deriveExcerpt(cleanBody);
  const blocks    = markdownToBlocks(cleanBody);

  // `pages` table schema (see 053_create_pages_table.sql): content jsonb,
  // status 'draft'|'published' (not a boolean), description TEXT. We ship
  // status='draft' so the admin flips visibility from /admin/cms/pages.
  const payload = {
    title,
    slug:            targetSlug,
    description:     excerpt,
    content:         blocks,
    status:          'draft',
    show_in_menu:    false,
    meta_title:      title.slice(0, 60),
    meta_desc:       excerpt.slice(0, 160),
    og_image:        '',
    // GEO metadata (added by 20260422000003_pages_geo_category.sql).
    category:        'geo',
    area_slug:       areaSlug,
    issue_slug:      issueSlug,
    source_draft_id: id,
  };

  if (existing) {
    const { data, error } = await sb
      .from('pages')
      .update(payload)
      .eq('id', existing.id)
      .select()
      .single();
    if (error) return pgError(error);
    return ok({ page: data, created: false });
  }

  const { data, error } = await sb
    .from('pages')
    .insert(payload)
    .select()
    .single();
  if (error) return pgError(error);
  return ok({ page: data, created: true });
});
