import Anthropic from '@anthropic-ai/sdk';
import { AnthropicError } from './errors';

/**
 * Configuration for Anthropic content generation
 */
export interface AnthropicGenerateOptions {
  model?: string;
  temperature?: number;
  maxTokens?: number;
  timeout?: number;
}

/**
 * Result from Anthropic content generation
 */
export interface AnthropicGeneratedContent {
  content: string;
  metadata?: Record<string, unknown>;
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
}


/**
 * Model mapping from OpenAI to Anthropic equivalents
 */
const MODEL_MAPPING: Record<string, string> = {
  'gpt-4o': 'claude-3-5-sonnet-20241022',
  'gpt-4o-mini': 'claude-3-5-haiku-20241022',
  'gpt-4': 'claude-3-opus-20240229',
  'gpt-3.5-turbo': 'claude-3-5-haiku-20241022',
};

/**
 * Shared Anthropic service for content generation
 * Mirrors OpenAI service structure for consistency
 */
export class AnthropicService {
  private client: Anthropic | null = null;

  /**
   * Initialize Anthropic client (lazy initialization)
   */
  private getClient(): Anthropic {
    if (!this.client) {
      const apiKey = process.env.ANTHROPIC_API_KEY;
      if (!apiKey) {
        throw new AnthropicError(
          'Anthropic API key not configured',
          'MISSING_API_KEY',
          { statusCode: 500 }
        );
      }
      this.client = new Anthropic({ apiKey });
    }
    return this.client;
  }

  /**
   * Map OpenAI model to Anthropic equivalent
   */
  private mapModel(openaiModel: string): string {
    return MODEL_MAPPING[openaiModel] || 'claude-3-5-sonnet-20241022';
  }

  /**
   * Generate content using Anthropic with proper error handling and timeouts
   * 
   * @param systemPrompt - System message defining the AI's role
   * @param userPrompt - User message with the generation request
   * @param options - Generation options (model, temperature, etc.)
   * @returns Generated content with metadata
   * @throws AnthropicError if generation fails
   */
  async generateContent(
    systemPrompt: string,
    userPrompt: string,
    options: AnthropicGenerateOptions = {}
  ): Promise<AnthropicGeneratedContent> {
    const {
      model = 'gpt-4o', // Accept OpenAI model names for compatibility
      temperature = 0.7,
      maxTokens = 4000,
      timeout = 60000, // 60 seconds
    } = options;

    // Validate inputs
    if (!systemPrompt?.trim()) {
      throw new AnthropicError(
        'System prompt is required',
        'INVALID_INPUT',
        { statusCode: 400 }
      );
    }
    if (!userPrompt?.trim()) {
      throw new AnthropicError(
        'User prompt is required',
        'INVALID_INPUT',
        { statusCode: 400 }
      );
    }

    // Sanitize prompts (prevent injection)
    const sanitizedSystem = this.sanitizePrompt(systemPrompt);
    const sanitizedUser = this.sanitizePrompt(userPrompt);

    // Map OpenAI model to Anthropic equivalent
    const anthropicModel = this.mapModel(model);

    const client = this.getClient();
    const startTime = Date.now();

    try {
      // Create timeout promise
      const timeoutPromise = new Promise<never>((_, reject) => {
        setTimeout(() => {
          reject(new AnthropicError(
            'Anthropic request timed out',
            'TIMEOUT',
            { statusCode: 504 }
          ));
        }, timeout);
      });

      // For JSON responses, add instruction to system prompt
      const enhancedSystem = sanitizedSystem.includes('JSON') || sanitizedSystem.includes('json')
        ? `${sanitizedSystem}\n\nIMPORTANT: Return ONLY valid JSON. No markdown, no code fences, no explanation.`
        : sanitizedSystem;

      // Race between Anthropic call and timeout
      const message = await Promise.race([
        client.messages.create({
          model: anthropicModel,
          max_tokens: maxTokens,
          temperature: temperature,
          system: enhancedSystem,
          messages: [
            { role: 'user', content: sanitizedUser },
          ],
        }),
        timeoutPromise,
      ]);

      const content = message.content[0]?.type === 'text' 
        ? message.content[0].text 
        : '';

      if (!content) {
        throw new AnthropicError(
          'No content generated by Anthropic',
          'EMPTY_RESPONSE',
          { statusCode: 500 }
        );
      }

      // Log usage for cost tracking
      const duration = Date.now() - startTime;
      this.logUsage({
        model: anthropicModel,
        inputTokens: message.usage.input_tokens,
        outputTokens: message.usage.output_tokens,
        totalTokens: message.usage.input_tokens + message.usage.output_tokens,
        duration,
      });

      return {
        content,
        usage: {
          promptTokens: message.usage.input_tokens,
          completionTokens: message.usage.output_tokens,
          totalTokens: message.usage.input_tokens + message.usage.output_tokens,
        },
      };
    } catch (error) {
      throw AnthropicError.fromAPIError(error);
    }
  }

  /**
   * Sanitize prompt to prevent injection attacks
   */
  private sanitizePrompt(prompt: string): string {
    // Remove potential injection patterns
    return prompt
      .replace(/```/g, '') // Remove code blocks
      .replace(/<script>/gi, '') // Remove script tags
      .replace(/javascript:/gi, '') // Remove javascript: protocol
      .trim();
  }

  /**
   * Log usage for cost tracking and monitoring
   */
  private logUsage(usage: {
    model: string;
    inputTokens: number;
    outputTokens: number;
    totalTokens: number;
    duration: number;
  }): void {
    // Calculate approximate cost (Claude 3.5 Sonnet pricing as of 2024)
    const inputCostPer1k = 0.003; // $3 per 1M tokens
    const outputCostPer1k = 0.015; // $15 per 1M tokens
    
    const inputCost = (usage.inputTokens / 1000) * inputCostPer1k;
    const outputCost = (usage.outputTokens / 1000) * outputCostPer1k;
    const totalCost = inputCost + outputCost;

    console.log('[Anthropic Usage]', {
      model: usage.model,
      tokens: {
        input: usage.inputTokens,
        output: usage.outputTokens,
        total: usage.totalTokens,
      },
      cost: {
        input: `$${inputCost.toFixed(4)}`,
        output: `$${outputCost.toFixed(4)}`,
        total: `$${totalCost.toFixed(4)}`,
      },
      duration: `${usage.duration}ms`,
      timestamp: new Date().toISOString(),
    });
  }
}

/**
 * Singleton instance of Anthropic service
 */
export const anthropicService = new AnthropicService();
