import OpenAI from 'openai';
import { OpenAIError } from './errors';

/**
 * Configuration for OpenAI content generation
 */
export interface GenerateOptions {
  model?: string;
  temperature?: number;
  maxTokens?: number;
  timeout?: number;
}

/**
 * Result from content generation
 */
export interface GeneratedContent {
  content: string;
  metadata?: Record<string, unknown>;
  usage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
}


/**
 * Shared OpenAI service for content generation
 * Handles rate limiting, error handling, cost tracking, and timeouts
 */
export class OpenAIService {
  private client: OpenAI | null = null;

  /**
   * Initialize OpenAI client (lazy initialization)
   */
  private getClient(): OpenAI {
    if (!this.client) {
      const apiKey = process.env.OPENAI_API_KEY;
      if (!apiKey) {
        throw new OpenAIError(
          'OpenAI API key not configured',
          'MISSING_API_KEY',
          { statusCode: 500 }
        );
      }
      this.client = new OpenAI({ apiKey });
    }
    return this.client;
  }

  /**
   * Generate content using OpenAI with proper error handling and timeouts
   * 
   * @param systemPrompt - System message defining the AI's role
   * @param userPrompt - User message with the generation request
   * @param options - Generation options (model, temperature, etc.)
   * @returns Generated content with metadata
   * @throws OpenAIError if generation fails
   */
  async generateContent(
    systemPrompt: string,
    userPrompt: string,
    options: GenerateOptions = {}
  ): Promise<GeneratedContent> {
    const {
      model = 'gpt-4o',
      temperature = 0.7,
      maxTokens = 4000,
      timeout = 60000, // 60 seconds
    } = options;

    // Validate inputs
    if (!systemPrompt?.trim()) {
      throw new OpenAIError(
        'System prompt is required',
        'INVALID_INPUT',
        { statusCode: 400 }
      );
    }
    if (!userPrompt?.trim()) {
      throw new OpenAIError(
        'User prompt is required',
        'INVALID_INPUT',
        { statusCode: 400 }
      );
    }

    // Sanitize prompts (prevent injection)
    const sanitizedSystem = this.sanitizePrompt(systemPrompt);
    const sanitizedUser = this.sanitizePrompt(userPrompt);

    const client = this.getClient();
    const startTime = Date.now();

    try {
      // Create timeout promise
      const timeoutPromise = new Promise<never>((_, reject) => {
        setTimeout(() => {
          reject(new OpenAIError(
            'OpenAI request timed out',
            'TIMEOUT',
            { statusCode: 408 }
          ));
        }, timeout);
      });

      // Race between OpenAI call and timeout
      const completion = await Promise.race([
        client.chat.completions.create({
          model,
          messages: [
            { role: 'system', content: sanitizedSystem },
            { role: 'user', content: sanitizedUser },
          ],
          temperature,
          max_tokens: maxTokens,
          response_format: { type: 'json_object' },
        }),
        timeoutPromise,
      ]);

      const content = completion.choices[0]?.message?.content;
      if (!content) {
        throw new OpenAIError(
          'No content generated by OpenAI',
          'EMPTY_RESPONSE',
          { statusCode: 500 }
        );
      }

      // Log usage for cost tracking
      const duration = Date.now() - startTime;
      this.logUsage({
        model,
        promptTokens: completion.usage?.prompt_tokens ?? 0,
        completionTokens: completion.usage?.completion_tokens ?? 0,
        totalTokens: completion.usage?.total_tokens ?? 0,
        duration,
      });

      return {
        content,
        usage: {
          promptTokens: completion.usage?.prompt_tokens ?? 0,
          completionTokens: completion.usage?.completion_tokens ?? 0,
          totalTokens: completion.usage?.total_tokens ?? 0,
        },
      };
    } catch (err) {
      throw OpenAIError.fromAPIError(err);
    }
  }

  /**
   * Sanitize prompt to prevent injection attacks
   */
  private sanitizePrompt(prompt: string): string {
    // Remove potential injection patterns
    return prompt
      .replace(/```/g, '') // Remove code blocks
      .replace(/<script>/gi, '') // Remove script tags
      .replace(/javascript:/gi, '') // Remove javascript: protocol
      .trim();
  }

  /**
   * Log usage for cost tracking and monitoring
   */
  private logUsage(usage: {
    model: string;
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
    duration: number;
  }): void {
    // Calculate approximate cost (GPT-4o pricing as of 2024)
    const inputCostPer1k = 0.005; // $5 per 1M tokens
    const outputCostPer1k = 0.015; // $15 per 1M tokens
    
    const inputCost = (usage.promptTokens / 1000) * inputCostPer1k;
    const outputCost = (usage.completionTokens / 1000) * outputCostPer1k;
    const totalCost = inputCost + outputCost;

    console.log('[OpenAI Usage]', {
      model: usage.model,
      tokens: {
        prompt: usage.promptTokens,
        completion: usage.completionTokens,
        total: usage.totalTokens,
      },
      cost: {
        input: `$${inputCost.toFixed(4)}`,
        output: `$${outputCost.toFixed(4)}`,
        total: `$${totalCost.toFixed(4)}`,
      },
      duration: `${usage.duration}ms`,
      timestamp: new Date().toISOString(),
    });
  }
}

/**
 * Singleton instance of OpenAI service
 */
export const openaiService = new OpenAIService();
