-- Migration: Seed issues batch 2 (issues 4-8)

INSERT INTO issues (rank, slug, icon, severity, title, anchor_stat, short_desc, definition, australian_data, mechanisms, impacts, groups, sources) VALUES
(4, 'bullying', '👊', 'critical',
 'Bullying at School',
 '46,000+ bullying incidents recorded in Queensland schools in 2023 alone',
 'School bullying remains pervasive and underreported across Australia. The absence of consistent national data collection is itself a governance failure that this site documents explicitly.',
 'Bullying is repeated, intentional aggressive behaviour directed at an individual where there is a perceived power imbalance. It includes physical, verbal, relational, and online forms. Repetition and power differential are defining features — a one-off conflict between equals is not bullying.',
 'Australia lacks a single consistent national bullying prevalence rate, explicitly noted in the Department of Education''s anti-bullying rapid review consultation paper, due to inconsistent data collection across jurisdictions. The Queensland Auditor-General''s Report 6 (2024–25) recorded over 46,000 incidents in Queensland state schools in 2023. This national data gap is disclosed on this site as a governance limitation.',
 'Bullying causes chronic stress activation. Victims experience hypervigilance, fear of school, and shame. These directly impair learning through attention deficit, emotional dysregulation, and avoidance behaviours. Witnesses also experience elevated stress. School climate deteriorates when bullying goes unaddressed.',
 '[{"title":"Attendance","text":"Bullying victims frequently become school avoiders. Chronic absence follows unresolved bullying situations."},{"title":"Mental Health","text":"Victimisation significantly increases risk of depression, anxiety, and suicidal ideation."},{"title":"Academic Performance","text":"The cognitive load of threat-vigilance directly displaces learning-directed attention."},{"title":"Social Trust","text":"Peer relationships become sources of threat rather than support, belonging, and development."}]'::jsonb,
 '["LGBTQ+ students (elevated target rate)","Students with disabilities","Aboriginal & Torres Strait Islander students","Students of non-English-speaking backgrounds","Students with visible difference"]'::jsonb,
 '["Queensland Auditor-General Report 6 (2024–25)","AIHW Australia''s Children: In Brief","Department of Education Anti-Bullying Rapid Review Consultation Paper"]'::jsonb),

(5, 'cyberbullying', '📱', 'critical',
 'Cyberbullying',
 '53% of 10–17 year olds experienced cyberbullying; 38% in the past 12 months',
 'Cyberbullying has erased the boundary between school and home. For many children, the torment follows them to bed. Australia''s eSafety Commissioner leads the world in documenting this crisis.',
 'Cyberbullying is online bullying using digital technology — including social media, messaging platforms, gaming environments, and email. It includes harassment, spreading rumours, exclusion, sharing embarrassing images, and impersonation. Unlike traditional bullying, it occurs 24/7 and can reach a global audience.',
 'The eSafety Commissioner''s research found 53% of 10–17 year olds had experienced cyberbullying at some point, and 38% in the past 12 months. Near-universal platform use among Australian teenagers means almost all children are at exposure risk. Harmful content including hate, violence, and pro-self-harm material is widely encountered.',
 'The always-on nature of cyberbullying means there is no safe refuge — not home, not the weekend, not school holidays. Constant threat monitoring, social status anxiety, and the viral amplification of humiliation create acute and chronic stress. Sleep disruption from late-night phone checking compounds the mental health damage significantly.',
 '[{"title":"Sleep & Fatigue","text":"Night-time notification checking disrupts sleep, compounding mental health and attention problems."},{"title":"School Avoidance","text":"When cyberbullying involves classmates, schools become unsafe — triggering refusal and absence."},{"title":"Emotional Regulation","text":"Constant digital threat monitoring increases emotional reactivity and reduces frustration tolerance."},{"title":"Self-Esteem","text":"Public humiliation at scale erodes self-worth during developmentally critical years."}]'::jsonb,
 '["Girls aged 10–17 (higher prevalence)","Students on image-based platforms","LGBTQ+ youth (higher severity)","High-social-media-use teens","Students already experiencing social anxiety"]'::jsonb,
 '["eSafety Commissioner — Online Experiences of Children in Australia","eSafety Commissioner — Cyberbullying Snapshot","Black Dog Institute Teens & Screens 2024"]'::jsonb),

(6, 'online-hate', '🌐', 'high',
 'Online Hate, Harassment & Harmful Content',
 'eSafety documents widespread exposure to hate, harmful content, and online harassment among Australian children',
 'Australian children''s online environments are saturated with hate, extremism, and harmful content. Exposure is not rare — it is routine. Schools cannot control the digital world children inhabit.',
 'Online hate includes content targeting individuals or groups based on race, religion, gender, sexuality, or disability. Harmful content includes graphic violence, pro-eating-disorder material, self-harm encouragement, and extremist ideology. Harassment is targeted, repeated digital abuse.',
 'The eSafety Commissioner''s research documents that harmful content is widely encountered online by Australian children, including racist, violent, and hateful material. Children from marginalised communities encounter identity-based hate at higher rates. The same platforms where friendships form are also spaces where hate consistently thrives.',
 'Repeated exposure to dehumanising content normalises aggression and prejudice. For targeted children, online hate functions like bullying — creating shame, hypervigilance, and identity-threat stress. Pro-self-harm communities can escalate vulnerable young people toward crisis. Algorithmic amplification means exposure is not accidental or random.',
 '[{"title":"Identity & Belonging","text":"Racialised hate undermines cultural identity, sense of belonging, and school engagement."},{"title":"Radicalisation Risk","text":"Extremist content can fill emotional voids in disconnected or bullied teenagers."},{"title":"Mental Health","text":"Chronic exposure to hate and violence content correlates with anxiety and depression."},{"title":"Social Trust","text":"Online harassment erodes trust in both digital and real-world social environments."}]'::jsonb,
 '["Students of racial and ethnic minorities","LGBTQ+ youth","Students with religious visibility","Teens experiencing social rejection","Boys on gaming platforms"]'::jsonb,
 '["eSafety Commissioner — Online Experiences of Children in Australia","eSafety Commissioner — Harmful Content Research","Mission Australia Youth Survey 2024"]'::jsonb),

(7, 'school-belonging', '🏫', 'high',
 'School Belonging & Connectedness',
 'NSW CESE evidence links belonging directly to lower bullying and better academic outcomes',
 'A child who doesn''t feel they belong at school is unlikely to succeed in it. Belonging is not a soft goal — it is a measurable, evidence-based predictor of wellbeing, learning, and retention.',
 'School belonging refers to a student''s subjective sense of being accepted, valued, and included by teachers and peers. Key dimensions include having supportive adults, positive peer relationships, feeling safe, and experiencing inclusion. A student can be physically present but psychologically absent.',
 'The Productivity Commission''s RoGS 2026 describes how jurisdictions collect belonging data through student surveys. NSW CESE research documents that strong belonging is linked to lower bullying victimisation and better academic engagement. Belonging scores have declined nationally in the post-COVID period.',
 'Belonging is a fundamental human need. In the school context, it activates intrinsic motivation and reduces threat-based learning blockers. When a student feels they belong, they take intellectual risks, ask for help, and persist through challenges. Without belonging, school becomes a source of shame rather than a place of growth.',
 '[{"title":"Motivation","text":"Belonging is the strongest non-academic predictor of intrinsic learning motivation."},{"title":"Help-Seeking","text":"Students with high belonging are significantly more likely to seek help from teachers."},{"title":"Bullying","text":"Strong belonging culture is consistently associated with substantially lower bullying prevalence."},{"title":"Retention","text":"Belonging deficits are a leading predictor of early school leaving."}]'::jsonb,
 '["Students transitioning to secondary school","Recently arrived migrant students","LGBTQ+ students","Students in low-SES communities","Students with disabilities"]'::jsonb,
 '["Productivity Commission RoGS 2026 — school education","NSW CESE Belonging Research","Mission Australia Youth Survey 2024"]'::jsonb),

(8, 'attendance-disengagement', '📉', 'high',
 'Attendance Decline & Disengagement',
 '57% average attendance in very remote schools vs 93% in major cities — RoGS 2026',
 'Australia''s school attendance crisis is starkest in remote communities, but is worsening nationally. Every missed day compounds learning loss and disconnection in ways that are hard to reverse.',
 'Attendance is the proportion of possible school days attended. Chronic absenteeism typically means missing 10% or more of school days. Disengagement is broader — a student can be present but cognitively, emotionally, or behaviourally disengaged. Both are measured in the Report on Government Services.',
 'RoGS 2026 reports national attendance by remoteness category, showing a steep gradient: major cities ~93%, inner regional ~90%, outer regional ~87%, remote ~80%, and very remote ~57%. Aboriginal and Torres Strait Islander students face compounded challenges. Secondary school attendance declines progressively through Year 10.',
 'Non-attendance creates compound learning loss — skills build on each other, and gaps widen exponentially over time. Disengagement signals that the school environment is not meeting the student''s psychological needs. Mental health conditions including anxiety and depression are among the most common causes of medically-justified absence.',
 '[{"title":"Learning Loss","text":"Each missed day means lost instruction, missed transitions, and widened skill gaps."},{"title":"Social Connection","text":"Absence disrupts peer relationship formation — a critical developmental need in school years."},{"title":"Long-term Outcomes","text":"Chronic absence in primary school is a predictor of Year 12 non-completion."},{"title":"Equity","text":"Remote, Indigenous, and low-SES students face compounding structural barriers to attendance."}]'::jsonb,
 '["Remote and very remote students","Aboriginal & Torres Strait Islander students","Students experiencing housing instability","Students with untreated mental health conditions","Students from low-SES families"]'::jsonb,
 '["Productivity Commission RoGS 2026 — school education","AIHW Australia''s Children","Australian Curriculum, Assessment and Reporting Authority"]'::jsonb);
