-- ═════════════════════════════════════════════════════════════════════════════
-- content_drafts — the single table behind the Content Creator admin section.
--
-- One row = one draft at any stage of the pipeline. The `status` column drives
-- the state machine (idea → approved_idea → generating → draft → verifying →
-- verified | rejected | archived). Ideas and finished content share the same
-- table so the UI can filter by status rather than joining across entities.
--
-- Key rules enforced at the database level:
--   • `social` posts MUST NOT have a title (title IS NULL).
--   • `blog` and `newsletter` drafts MUST have a non-empty title.
--   • `platform` only applies to social posts.
-- ═════════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS content_drafts (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  content_type  TEXT NOT NULL
                CHECK (content_type IN ('social', 'blog', 'newsletter')),

  -- Only meaningful when content_type = 'social'. NULL otherwise.
  platform      TEXT
                CHECK (platform IS NULL
                       OR platform IN ('twitter','linkedin','facebook','instagram')),

  status        TEXT NOT NULL DEFAULT 'idea'
                CHECK (status IN (
                  'idea',           -- generated by stage 1, awaiting approval
                  'approved_idea',  -- user approved, ready to generate content
                  'generating',     -- edge fn running OpenAI→Anthropic chain
                  'draft',          -- content written, awaiting verification
                  'verifying',      -- edge fn checking claims against vault
                  'verified',       -- all claims traced to vault, ready for team
                  'rejected',       -- flagged claims not in vault, back to editor
                  'archived'        -- soft-deleted
                )),

  title         TEXT,
  body          TEXT NOT NULL DEFAULT '',

  -- Original user brief: { topic, tone, audience, keywords[], vault_category }
  brief         JSONB NOT NULL DEFAULT '{}'::jsonb,

  -- Provenance from the AI chain:
  --   { openai_model, anthropic_model, tokens, provider, fallback_used,
  --     generated_at, verified_at }
  ai_metadata   JSONB NOT NULL DEFAULT '{}'::jsonb,

  -- Verification verdict:
  --   { status, confidence, notes, supported_claims[], flagged_claims[],
  --     checked_at }
  verification  JSONB NOT NULL DEFAULT '{}'::jsonb,

  -- vault_content ids used as RAG context during generation/verification.
  vault_refs    UUID[] NOT NULL DEFAULT '{}',

  created_by    TEXT NOT NULL DEFAULT 'admin',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Title enforcement per content type.
  CONSTRAINT title_rules CHECK (
    (content_type = 'social' AND title IS NULL)
    OR
    (content_type IN ('blog','newsletter') AND title IS NOT NULL AND length(trim(title)) > 0)
  ),

  -- Platform only meaningful for social.
  CONSTRAINT platform_only_for_social CHECK (
    (content_type = 'social') OR (platform IS NULL)
  )
);

-- ── Indexes for the common admin queries ────────────────────────────────────
CREATE INDEX IF NOT EXISTS content_drafts_status_idx
  ON content_drafts(status);

CREATE INDEX IF NOT EXISTS content_drafts_type_status_idx
  ON content_drafts(content_type, status);

CREATE INDEX IF NOT EXISTS content_drafts_updated_idx
  ON content_drafts(updated_at DESC);

-- GIN index on brief/verification for filtering by topic, tags, etc.
CREATE INDEX IF NOT EXISTS content_drafts_brief_gin
  ON content_drafts USING GIN (brief);

-- ── RLS: admin-only. Reads and writes require authenticated role. ───────────
ALTER TABLE content_drafts ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'content_drafts' AND policyname = 'Auth read content_drafts'
  ) THEN
    CREATE POLICY "Auth read content_drafts"
      ON content_drafts FOR SELECT
      USING (auth.role() = 'authenticated');
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'content_drafts' AND policyname = 'Auth write content_drafts'
  ) THEN
    CREATE POLICY "Auth write content_drafts"
      ON content_drafts FOR ALL
      USING (auth.role() = 'authenticated');
  END IF;
END $$;

-- ── updated_at trigger (reuses the existing set_updated_at() function) ──────
DROP TRIGGER IF EXISTS content_drafts_updated_at ON content_drafts;
CREATE TRIGGER content_drafts_updated_at
  BEFORE UPDATE ON content_drafts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── Documentation ───────────────────────────────────────────────────────────
COMMENT ON TABLE content_drafts IS
  'Admin Content Creator pipeline. One row per draft, status drives the state machine.';
COMMENT ON COLUMN content_drafts.brief IS
  'User input: { topic, tone, audience, keywords[], vault_category }';
COMMENT ON COLUMN content_drafts.verification IS
  'Anthropic verdict: { status, confidence, supported_claims[], flagged_claims[], notes }';
COMMENT ON COLUMN content_drafts.vault_refs IS
  'vault_content ids used as RAG context. Every factual claim should map to one.';
